inp = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

inp = [i for i in inp.split("\n") if i]

inds = [False] * len(inp[0])

for i in range(len(inp[0])):
    if inp[0][i] == "S":
        inds[i] = True

r = 0
for i in range(1, len(inp)):
    for j in range(len(inp[i])):
        if inp[i][j] == "^":
            if inds[j]:
                inds[j] = False
                r += 1
                inds[j + 1] = True
                inds[j - 1] = True

print(r)