inp = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

inp = [i for i in inp.split("\n") if i]

inds = [0] * len(inp[0])

for i in range(len(inp[0])):
    if inp[0][i] == "S":
        inds[i] = 1

for i in range(1, len(inp)):
    indsN = [0] * len(inp[0])
    for j in range(len(inp[i])):
        if inp[i][j] == "^":
            if inds[j]:
                indsN[j + 1] += inds[j]
                indsN[j - 1] += inds[j]
        else:
            indsN[j] += inds[j]
    inds = indsN

print(sum(inds))